name: Android CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'webapp/**'
      - '**.md'
      - 'project-resources/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'webapp/**'
      - '**.md'
      - 'project-resources/**'
  # This allows manual triggering of the workflow
  # Go to the "Actions" tab in the repository, select this workflow, and click the "Run workflow" button to run it manually.
  workflow_dispatch:

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '23'
          distribution: 'temurin'

      # Automatic gradle caching using `actions/cache@v4`
      # https://github.com/gradle/actions/tree/main/setup-gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Test, build, and lint
        run: ./gradlew testDebugUnitTest assembleDebug lintKotlin --parallel --daemon
